[package]
name = "smartcontent_aggregator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.34"
rss = "2.0"
scraper ="0.19"
actix-web = "4.0"
structopt = "0.3"
tokio = { version = "1.0", features = ["full"] }
dotenv = "0.15.0"
env_logger = "0.11.3"
log = "0.4.21"
config = "0.14.0"
